### PR TITLE
fix(nx-plugin): Incorrect handling of package generation in subdirectories

### LINKED ISSUE #180: Generating a package in a subdirectory fails
At the very least, the license generator is being passed the wrong project name (eg, when generating `frontend/web` it just gets passed `web` instead of `frontend-web`, which is the actual package name registered with Nx). Workaround is to eg generate `frontend/web` as `frontend-web` and the rename/move the directory, change the directory in the release-please config, etc

### PR DESCRIPTION
**Pull request by luxaritas**
Resolves #180

### CODE REVIEW

File: packages/nx-plugin/src/generators/package/vue/app/index.ts [hunk 1]
```diff
@@ -1,39 +1,29 @@
...
 import generateWebApp from '../../web/app';
 import generateCypressCt from '../../cypress/ct';
 import { installDependencies, installDevDependencies } from '@/utils/dependencies';
+import getPackageNames from '@/utils/names';
 
 interface Schema {
   name: string;
   description: string;
-  directory: string;
+  directory?: string;
```
Comment (tkaragianes) [inline packages/nx-plugin/src/generators/package/vue/app/index.ts:16]: Why are directories optional in some of the generators?

Comment (luxaritas) [reply packages/nx-plugin/src/generators/package/vue/app/index.ts:16]: By default, the directory will be automatically determined based on the name.

**Review by tkaragianes — APPROVED** [review]
